Repository Anirudh4583/go-gin-template, pull requests merged in 2023-03, with the labels that each got.

#3 database setup
  main.go
  models/models.go
Labels: changes-requested

#5 Added Docker support
  .gitignore
  Dockerfile
  docker-compose.yml
  models/models.go
  pkg/setting/setting.go
Labels: ready-for-review

#6 added pkg/e for error message
  pkg/e/code.go
  pkg/e/msg.go
Labels: can-be-merged
